<?php return array (
  0 => 'id,orderid,uid,shid,cpid,name,tupian,jine,num,canshu,type,off,kahao,kamima,beizhu,biaoshi,ctime,atime,ip,mhash,huobi,tehui,level,kuaiid,kuaitype,kuaijil,miaosufen,fuwufen,wuliufen,pinguser,pingoff,pingtime,pingname,miaoshu,ptupian,ptupianji',
  1 => 
  array (
    'id' => 'auto_increment',
    'orderid' => 'orderid_',
    'uid' => 'uid_0',
    'shid' => 'shid_0',
    'cpid' => 'cpid_0',
    'name' => 'name_',
    'tupian' => 'tupian_',
    'jine' => 'jine_0.00',
    'num' => 'num_0',
    'canshu' => 'canshu_',
    'type' => 'type_0',
    'off' => 'off_0',
    'kahao' => 'kahao_',
    'kamima' => 'kamima_',
    'beizhu' => 'beizhu_',
    'biaoshi' => 'biaoshi_',
    'ctime' => 'ctime_0',
    'atime' => 'atime_0',
    'ip' => 'ip_',
    'mhash' => 'mhash_',
    'huobi' => 'huobi_0',
    'tehui' => 'tehui_1.00',
    'level' => 'level_0',
    'kuaiid' => 'kuaiid_0',
    'kuaitype' => 'kuaitype_0',
    'kuaijil' => 'kuaijil_0',
    'miaosufen' => 'miaosufen_0.0',
    'fuwufen' => 'fuwufen_0.0',
    'wuliufen' => 'wuliufen_0.0',
    'pinguser' => 'pinguser_',
    'pingoff' => 'pingoff_0',
    'pingtime' => 'pingtime_0',
    'pingname' => 'pingname_',
    'miaoshu' => 'miaoshu_',
    'ptupian' => 'ptupian_',
    'ptupianji' => 'ptupianji_',
  ),
);