<?php return array (
  0 => 'id,name,guanjian,miaoshu,cid,url,http,listmb,neromb,leixin,uid,shid,adminid,tuijian,paixu,renqi,tupian,tupianji,neirong,kuozan,kuozanform,atime,xtime,xianoff,off,explx1,explx2,explx3,explx4,explx5,explx6,beizhu',
  1 => 
  array (
    'id' => 'auto_increment',
    'name' => 'name_',
    'guanjian' => 'guanjian_',
    'miaoshu' => 'miaoshu_',
    'cid' => 'cid_0',
    'url' => 'url_',
    'http' => 'http_',
    'listmb' => 'listmb_',
    'neromb' => 'neromb_',
    'leixin' => 'leixin_1',
    'uid' => 'uid_0',
    'shid' => 'shid_0',
    'adminid' => 'adminid_0',
    'tuijian' => 'tuijian_0',
    'paixu' => 'paixu_0',
    'renqi' => 'renqi_0',
    'tupian' => 'tupian_',
    'tupianji' => 'tupianji_',
    'neirong' => 'neirong_',
    'kuozan' => 'kuozan_',
    'kuozanform' => 'kuozanform_',
    'atime' => 'atime_0',
    'xtime' => 'xtime_0',
    'xianoff' => 'xianoff_0',
    'off' => 'off_0',
    'explx1' => 'explx1_',
    'explx2' => 'explx2_',
    'explx3' => 'explx3_',
    'explx4' => 'explx4_',
    'explx5' => 'explx5_',
    'explx6' => 'explx6_',
    'beizhu' => 'beizhu_',
  ),
);